class ParseTree
  @type: ParseTreeType
  @value: String | nil
  @branches: Array[ParseTree] | nil

  def initialize: (parseTreeTypeSymbol type, String | nil value, Array[ParseTree] | nil branches) -> void
end

module ParseTreeType
  INT: :int
  PROG: :program
  FUNCTION: :function
  EXPR: :expr
  RETURN: :return
  VAR_USE: :var_use
end

type parseTreeTypeSymbol = :program | :function | :expr | :return