class Token
  attr_reader token_type: TokenType

  attr_reader token_value: String
end

module TokenType
  INT: :integer
  IDENT: :ident
  PLUS: :plus
  MINUS: :minus
  STAR: :star
  SLASH: :slash
  SEMIS: :semis
  L_PAREN: :l_paren
  R_PAREN: :r_paren
  L_BRACE: :l_brace
  R_BRACE: :r_brace
  COLON: :colon
end

type tokenTypeSymbol = :int | :ident | :semis | :l_paren | :r_paren | :l_brace | :r_brace | :colon